#!/usr/bin/env python3

from os import path, scandir
from import move, rmtree
from argparse import ArgumentParser

parser = ArgumentParser(description='Moves all nested files in a specified directory into itself')
group = parser.add_mutually_exclusive_group(required=True)
group.add_argument('-n', '--dry-run', action='store_true',
                   help='show which files will be moved and where')
group.add_argument('-f', '--force', action='store_true',
                   help='move all files and remove directories')
parser.add_argument('dir', metavar='DIR', help='directory to be flattened')
parser.add_argument('-v', '--verbose', action='store_true',
                    help='print paths while moving')
args = parser.parse_args()

realpath = path.realpath(args.dir)

dirs = []
files = []

# bc the find binary is different between macOS and Linux for some reason
# please don't judge me i am a python3 newbie

def find(path):
    if path.isdir(path):
        for i in scandir(path):
            find(i.path)
        if not realpath == path:
            dirs.append(path)
    else:
        files.append(path)

find(realpath)

for source in files:
    prefix = 'Moving' if args.force else 'Will move'
    dest = path.join(realpath, path.basename(path))
    print(f"{prefix} {source} -> {dest}")

    if args.force:
        move(source, dest)

for _dir in dirs:
    prefix = 'Deleting' if args.force else 'Will delete'
    print(f"{prefix} {_dir}")

    if args.force:
        rmtree(_dir)
